version: '3.4'

networks:
    grafana:
    prometheus:
    influxdb:

services:
    influxdb:
        image: influxdb:1.8
        networks:
            - grafana
            - influxdb
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=k6
            - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
        volumes:
            - ./influxdb/local-storage:/var/lib/influxdb

    grafana:
        image: grafana/grafana:latest
        user: "472"
        networks:
            - grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
            - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_AUTH_BASIC_ENABLED=true
            - GF_AUTH_ANONYMOUS_ENABLED=false
        volumes:
            - ./grafana/provisioning/:/etc/grafana/provisioning/
            - ./grafana/local-storage/:/var/lib/grafana/

    prometheus:
        image: prom/prometheus:v2.33.5
        command: --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml
        networks:
            - grafana
        ports:
            - "9999:9999"
        volumes:
            - ./prometheus:/prometheus
